package dem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String roll;

   public Customer()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getRoll()
   {
      return this.roll;
   }

   public void setRoll(java.lang.String roll)
   {
      this.roll = roll;
   }

   public Customer(java.lang.String name, java.lang.String roll)
   {
      this.name = name;
      this.roll = roll;
   }

}