package dem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResultOp implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private Double amount;

   public ResultOp()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Double getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Double amount)
   {
      this.amount = amount;
   }

   public ResultOp(java.lang.String name, java.lang.Double amount)
   {
      this.name = name;
      this.amount = amount;
   }

}