package dem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResultOp implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ResultOp() {
    }

}