package dem.pro1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Premium implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Double componentPremium;
   private java.lang.Double totalPremium;

   public Premium()
   {
   }

   public java.lang.Double getComponentPremium()
   {
      return this.componentPremium;
   }

   public void setComponentPremium(java.lang.Double componentPremium)
   {
      this.componentPremium = componentPremium;
   }

   public java.lang.Double getTotalPremium()
   {
      return this.totalPremium;
   }

   public void setTotalPremium(java.lang.Double totalPremium)
   {
      this.totalPremium = totalPremium;
   }

   public Premium(java.lang.Double componentPremium,
         java.lang.Double totalPremium)
   {
      this.componentPremium = componentPremium;
      this.totalPremium = totalPremium;
   }

}