package dem.pro1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Proposal implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private dem.pro1.GeneralDetail generalDetail;
   private dem.pro1.Coverages coverages;

   public Proposal()
   {
   }

   public dem.pro1.GeneralDetail getGeneralDetail()
   {
      return this.generalDetail;
   }

   public void setGeneralDetail(dem.pro1.GeneralDetail generalDetail)
   {
      this.generalDetail = generalDetail;
   }

   public dem.pro1.Coverages getCoverages()
   {
      return this.coverages;
   }

   public void setCoverages(dem.pro1.Coverages coverages)
   {
      this.coverages = coverages;
   }

   public Proposal(dem.pro1.GeneralDetail generalDetail,
         dem.pro1.Coverages coverages)
   {
      this.generalDetail = generalDetail;
      this.coverages = coverages;
   }

}