package dem.pro1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ReInsurance implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ReInsurance() {
    }

}