package dem.pro1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ReInsurance implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Double rate;

   public ReInsurance()
   {
   }

   public java.lang.Double getRate()
   {
      return this.rate;
   }

   public void setRate(java.lang.Double rate)
   {
      this.rate = rate;
   }

   public ReInsurance(java.lang.Double rate)
   {
      this.rate = rate;
   }

}